# Generated by Django 2.1.5 on 2022-02-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211202_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address_1', models.CharField(max_length=1000)),
                ('shipping_address_2', models.CharField(max_length=1000)),
                ('shipping_address_3', models.CharField(max_length=1000)),
            ],
        ),
    ]
