# Generated by Django 2.1.5 on 2022-02-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='Product',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
