# Generated by Django 2.1.5 on 2022-02-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='products',
            new_name='product',
        ),
    ]
