# Generated by Django 2.1.5 on 2022-02-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220211_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
